run:
  tests: true
  timeout: 5m
  concurrency: 10

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - unparam
    - misspell
    - nolintlint

issues:
  exclude-rules:
    - text: "leading space"
      linters:
        - nolintlint
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "ST1003:"
      linters:
        - stylecheck
    # FIXME: Disabled until golangci-lint updates stylecheck with this fix:
    # https://github.com/dominikh/go-tools/issues/389
    - text: "ST1016:"
      linters:
        - stylecheck
    - text: "SA1019: codec.LegacyAmino is deprecated"
      linters:
        - staticcheck
  max-issues-per-linter: 10000
  max-same-issues: 10000
